### ISSUE TITLE
SSH module active when it shouldn't be?

### ISSUE THREAD

**Issue by Tmplt** [Eriner/zim#30] opened 2016-02-04 18:24 UTC
I've created a small function to add SSH keys to `ssh-agent` on demand:

```sh
function git ssh () {
    # Does the agent handle any keys?
    ssh-add -l &>/dev/null

    # True if last executed command (ssh-add -l) exits non-zero.
    if [ $? -ne 0 ]; then
        ssh-add
    fi

    # Execute git or ssh with all parameters, and not this function
    command $0 "$@"
}
```

This works as expected when ZIM isn't sourced. But if it is, and `ssh-agent` doesn't handle any keys, `zsh` will ask for the key's pass phrase after every command, instead of just before `git` or `ssh`. My loaded modules are:

`zmodules=(directory environment git history input utility                                                                    syntax-highlighting history-substring-search prompt completion pacman)`.

Is this an issue with ZIM? Is there some `setopt` that causes this?

**Comment by Eriner** [comment] 2016-02-04 18:42
okay, your function name has a space. That means you are overriding `git` and `ssh`. When the prompt needs to call `git` to determine repo status (or you call `ssh`), it is running that function. Replace `function git ssh () {` with `git-ssh() {`

**Comment by Tmplt** [comment] 2016-02-04 18:57
Unfortunately, the issue remains.

**Comment by Eriner** [comment] 2016-02-04 19:02
oh, I see, you are **intentionally** wrapping the git and ssh functions to load a key if you don't have one loaded already. Sorry, I obviously didn't read the code clearly. If you've changed the function name above (to something like `git-ssh` that doesn't wrap `git` and `ssh`) and your problem still occurs without using the zim `ssh` module, then the problem isn't with Zim.

**Comment by Tmplt** [comment] 2016-02-04 19:20
I forgot to create a new shell, which is why the problem persisted.

The `git` function and `git` module clashes then? Could this be resolved by replacing every occurrence of `git` in the current prompt theme with `command git`, so ZIM ignores the function? Unfortunately I don't have time at the moment to delve into the code, but I will later.

**Comment by Eriner** [comment] 2016-02-04 19:21
As I've said before, most prompts will call `git` when inside a repo to add information to the prompt. Seeing as it is prompting for a password frequently, this is likely the cause. That means that `ssh-add` is not successfully adding any keys. Check if `ssh-add -l` lists any keys when using this function with Zim. If it produces nothing, then that is the problem. Otherwise, I have no idea why you're having this issue, especially since you don't have the `ssh` module loaded.

I'm going to mark this as "invalid" and close this issue, as I don't think this has anything to do with Zim directly. If new information reveals that this is a Zim problem, I'll change the status. 

Please keep posting here if you would like assistance in resolving your problem, I'm happy to help!

**Comment by Eriner** [comment] 2016-02-04 19:22
Decided to go with 'need info', as you have a point with replacing 'git' with 'command git'. That said, I still believe the ultimate problem is that your keys aren't being added with `ssh-add` in your function. That is the only reason it would prompt more than once.

**Comment by Eriner** [comment] 2016-02-04 19:23
Please check what I mentioned above to determine the root cause of your issue.

**Comment by Tmplt** [comment] 2016-02-04 19:43
Oh. I see your view now. To debug this issue I have manually removed the keys added to the agent so I could check whether the shell would prompt me for a pass phrase. Because of this I wrote that it asks after any and every command. Keys _are_ successfully added to the agent.

As I understand it: the prompt module will check if the current directory is used by git. To do this, prompt calls `$(which git)` (or something like it), and because my function is defined, it executes through it instead of calling `git` directly, which is possible with `command git [argument...]`.

Without delving into the code, I'm presuming that this issue could be fixed by calling `git` directly with `command`, and thus ignore the function under the same name.

**Comment by Eriner** [comment] 2016-02-04 19:50
Prompts likely need to swap `git` with `command git` to avoid hitting these issue. Issue is that @Tmplt doesn't want to be adding ssh keys unless `git` or `ssh` is called directly from the command line (not in a script or prompt).

**Comment by Eriner** [comment] 2016-02-04 20:02
The issue exists because vcs_info calls `git`, not `command git`
```
14:56 <Eriner> sneke: VCS_INFO calls git directly by name.
14:56 <Eriner> "if VCS_INFO_check_com ${vcs_comm[cmd]} && ${vcs_comm[cmd]} rev-parse --is-inside-work-tree &> /dev/null ; then"
14:56 <sneke> Well, you've got the function in the GitHub Issue, I only added some prints when it's it's called and when a pass is asked for
14:56 <Eriner> where ${vcs_comm[cmd]} == 'git'
14:56 <Eriner> so there's your problem.
14:56 <Eriner> Unless I'm wrong (and someone here can correct me)
14:57 <Eriner> but if you wrap 'git' with your own function, your function will be called whenever the prompt runs vcs_info
14:58 <sneke> can't I just ${command ${vcs_comm[cmd]}} ?
14:58 <sneke> I'm assuming vcs_info is something external?
14:58 <Eriner> Zsh module
14:58 <Eriner> https://github.com/zsh-users/zsh/tree/master/Functions/VCS_Info
14:59 <sneke> ah
14:59 <Eriner> Here: it will run git because 'git' is enabled in the prompt vcs zstyle: https://github.com/zsh-users/zsh/blob/master/Functions/VCS_Info/vcs_info#L109
15:00 <Eriner> and because it is set as 'git', it will run your wrapper function here: https://github.com/zsh-users/zsh/blob/master/Functions/VCS_Info/Backends/VCS_INFO_detect_git#L9
15:00 <Eriner> maybe this should be changed upstream in Zsh? Because I can't fix your problem. 
```

**Comment by Tmplt** [comment] 2016-02-04 21:20
Thanks to ft on #zsh on Freenode, adding `zstyle ':vcs_info:git:*:-all-' command =git` to `~/.zshrc` after ZIM has been sourced fixes this issue. ZIM now calls git directly.

**Comment by Eriner** [comment] 2016-02-04 21:36
Great. Glad you got it worked out.

**Closed by Eriner** 2016-02-04 21:36 UTC
Labels: upstream
