### ISSUE TITLE
Issues with prompt theme

### ISSUE THREAD

**Issue by irliao** [Eriner/zim#37] opened 2016-02-27 14:16 UTC
When using themes like "minimal" and "liquidprompt", the prompt responds very slow and commands such as "ls" takes long to output even in small directories. However, everything seems to work instantly when switched to "pure" or "bart". 

Is this expected behavior? (Using default .zimrc .zshrc .zlogin, only changing zprompt_theme= in .zimrc)

Also is there a way to modify "pure" theme so it does not output a new line after every command returns?

Thank You!

**Comment by Eriner** [comment] 2016-02-27 18:04
I need more information. When creating an issue, a template pops up with the things I require. https://github.com/Eriner/zim/blob/master/ISSUE_TEMPLATE.md

No, the pure theme is an external module and is not something I can change. You'd have to ask upstream about your newline request.

**Comment by irliao** [comment] 2016-02-27 19:17
Sorry for missing the template.

Here is the info from my side:
- zim commit ref:  b959569
- gist of .zimrc: https://gist.github.com/irliao/1ea7742dfd63ab160cfd#file-zimrc-zsh
- zsh version: 5.0.8 (x86_64-apple-darwin15.0)
- gist of .zshrc: https://gist.github.com/irliao/1ea7742dfd63ab160cfd#file-zshrc-zsh
- uname: Darwin 15.3.0 x86_64

Description: 
When using themes like "minimal" and "liquidprompt", the prompt responds very slow and commands such as "ls" takes long to output even in small directories.

Steps to reproduce:
1. Install Zim
2. Change theme from 'steeef' to 'minimal' in ~/.zimrc

Images of console output when holding down RETURN key:
- Current behavior: long delay between each outputs, using "minimal"
![screen shot 2016-02-27 at 11 09 43](https://cloud.githubusercontent.com/assets/2220087/13374766/b9dc63c2-dd42-11e5-8e8b-6240ba0f8f05.png)

- Expected behavior: almost no delay between outputs, using "gitster"
![screen shot 2016-02-27 at 11 12 47](https://cloud.githubusercontent.com/assets/2220087/13374781/193a3a6a-dd43-11e5-8e3a-4c32574f8e83.png)

Please let me know if more information is needed.

Thank You!

**Comment by Eriner** [comment] 2016-02-27 19:29
@irliao Try changing some of the git-related settings mentioned here: https://github.com/sindresorhus/pure#options

run `export SETTING_NAME=0` or whatever is required. See if that has any impact on your issue. If it does, add the `export`s to your `.zprofile`.

**Comment by irliao** [comment] 2016-02-28 03:05
@Eriner I tried changing those settings, but it did not seem to improve much, here is my gist:
https://gist.github.com/irliao/f4e6e1449ba7028aa965#file-zshrc-zsh

It seems like the slowness mostly occurs when navigating in a git repository.

**Comment by Eriner** [comment] 2016-02-28 03:25
Not sure what to tell you; I can't reproduce your issue.

**Comment by Eriner** [comment] 2016-02-28 03:27
It's very possible that the issue is due to a large repository and how those themes invoke specific git commands as opposed to using VCS info, but I'm not entirely sure.

**Comment by irliao** [comment] 2016-02-28 07:47
It seems like only "minimal" and a few other themes are experiencing slowness only in git repo directories. I will update you if I can pinpoint the root cause. Thank you so much for your help!!! :)

**Comment by Eriner** [comment] 2016-02-28 07:52
No problem! You might want to check how the themes implement their git status-lines if you discover themes with issues. Some call `git` directly in a subshell, others use VCS info. I would guess that the former is the causing the problem, but I haven't spent much time to investigate what the exact cause is.

**Comment by Eriner** [comment] 2016-02-28 07:54
I'm going to close this issue since I can't reproduce the issue, but if you find the cause or can pin the issue down, comment here and I'll be sure to follow up. Thanks!

**Closed by Eriner** 2016-02-28 07:54 UTC
