### ISSUE TITLE
Conflict with tmux attach

### ISSUE THREAD

**Issue by jmurinello** [Eriner/zim#39] opened 2016-03-15 13:19 UTC
Description
-----------
If I `cmd + Q` my terminal with a tmux session running and then open again the terminal and use `tmux attach` command to attach the same session, the terminal will attach the session like it was, the terminal will continue to work but it will stop rendering anything that I'm doing.

I notice though that if I use tmux `prefix + d` and detach the session, quit the terminal, open again, and `tmux attach` the session, everything works normally.

Steps to reproduce
------------------
Start a new tmux session.
`tmux new-session -s 0`

Quit terminal and re-open terminal.
`cmd + Q`
`cmd + Space`
`terminal + Enter`

Reattach session
`tmux attach -t 0`
Press `a` until terminal stops rendering

(if `a` stops to appear in the prompt)
Write `hello`
Use tmux prefix cmd
`prefix + c` to start a new tmux window
`prefix + n` to switch back to the first window and maybe you will see `aaaaaaaaaaaaaaaaaahello`

Why I think it's a zim conflict with tmux?
------------------
Because I deactivate the `zimrc` file, reproduced the same steps and tmux worked without any issue.
I'm not good at debugging these things but I notice that if I only use the `zmodules=(directory)` everything was ok, then `zmodules=(enviroment)` was also ok, but once I set `zmodules=(git)` the issue happaned. But even if I disabled the `git module` and enable the default ones, same issue.

Thanks,
jmurinello

**Comment by Tmplt** [comment] 2016-03-15 15:31
Tried to reproduce with [Termite](https://github.com/thestinger/termite), no success:

![no success](https://u.pomf.is/ioobap.png)

However, I'm not sure what you mean with "Press `a` until terminal stops rendering", because there is not character limit in my terminal emulator.

What is your current terminal emulator, and have you tried with any others? A wild guess is that your program is having trouble re-rendering highlighted text, which I believe Zim enables by default.

**Comment by jmurinello** [comment] 2016-03-15 16:08
In my case, the character appears 8 to 10 times and after that the terminal no longer renders. I can keep pressing the character and I know it will reproduce the same result as you but for me to see it I have to `prefix + c` `prefix + n`. I can still type but I will not see what I am doing unless I `prefix + n` twice.

I am using iterm2 but I also used the OSX El Capitan Terminal and both reproduced the same results.

I initially assumed it was a problem with `tmux` and even disabled my `tmux.conf`, but the same thing was happening until I disabled the code created in the `zshrc` while installing `zim`.

From there on I started to enable/disable zmodules.

Anyway, like I mention is something that doesn't happen if I detach the session before quitting the OSX Terminal / iterm2.

Just a side note: this is a fresh installment and everything is updated. `echo $SHELL` will point do `/bin/zsh` inside or outside tmux.

**Comment by Eriner** [comment] 2016-03-15 17:21
I can't reproduce this issue either. Please provide the information that is requested in the template (Zsh version, commit ref, etc).

**Comment by jmurinello** [comment] 2016-03-15 23:57
### Here you are:
- gist of .zimrc: https://gist.github.com/jmurinello/14a43c780efad9df3c2b
- Zsh version: zsh 5.2 (x86_64-apple-darwin15.3.0)
- gist of .zshrc: https://gist.github.com/jmurinello/51cd17dcb78e2862c700
- $(uname -msv): Darwin Kernel Version 15.3.0 x86_64

Both zimrc and zshrc are the ones generated by following you installation steps.

Something else could be provoking this issue. At first I thought it was `tmux` or `vim` so I disabled both tmux.conf and vimrc and the same thing happened. But as I mentioned as soon as I disabled the `zmodules` everything worked as expected with tmux.conf, vimrc and vim plugins both in OSX Terminal and iTerm2.

**Comment by Eriner** [comment] 2016-03-18 19:40
I still am unable to reproduce this. Is this a Mac specific issue?

**Comment by jmurinello** [comment] 2016-03-19 01:22
It could be. If anyone else with the same `uname -v` as mine could reproduce this issue. I don't know if that's the case of @Tmplt. Then I would have to assume it was just me.

**Comment by Tmplt** [comment] 2016-03-19 01:42
My output of `uname -v` is different, yes; 
`#1 ZEN SMP PREEMPT Thu Mar 10 12:43:55 UTC 2016` (Arch Linux with `linux-zen`)

**Comment by Eriner** [comment] 2016-04-02 20:41
I'm still unable to reproduce this issue. Can anyone else see if they can reproduce this issue only on a Mac machine? I'm curious as to if this is a Mac issue, a brew/Mac package (old) issue, or if this issue impacts Linux users as well.

**Comment by Eriner** [comment] 2016-05-08 06:36
Has anyone else been able to reproduce this issue? If not, I will close this issue.

**Comment by Eriner** [comment] 2016-05-14 21:19
Since no one has been able to reproduce this, I am going to close this issue. If someone is able to reproduce this and either fix this, or provide me with an environment where I can reproduce this, I'll reopen this issue.

**Closed by Eriner** 2016-05-14 21:19 UTC
Labels: need info
