### ISSUE TITLE
Input handling

### ISSUE THREAD

**Issue by GrayShade** [Eriner/zim#6] opened 2015-12-29 08:45 UTC
I tried to switch from `prezto` to `zim` and it certainly seems faster, but I'm having some trouble with the input mapping.

* `Ctrl-Left` and `Ctrl-Right` print their escape codes. I noticed that the `input` module doesn't set them up with `bindkey`, so it makes sense.
* I tried `bindkey '\e[1;5D' backward-word` and it works, but there is a delay or some kind of timeout (waiting for a different escape sequence?). This was with `TERM=putty-256color` or how it's called.
* From another machine with `TERM=xterm-256color` the cursor disappears when it's not at the end of line. This happens with `gnome-terminal`.

**Comment by Eriner** [comment] 2015-12-29 08:47
Ah, so this is a putty thing. I will investigate this, but I don't use putty (or Windows at all, for that matter). If you find any additional information, please let me know.

**Comment by GrayShade** [comment] 2015-12-29 08:51
I forgot to mention, those work fine in prezto and oh-my-zsh. I know that PuTTY sends `^[[1;5D`, but I know nothing about it doing anything special.

**Comment by Eriner** [comment] 2015-12-29 08:52
Right, I'm just not used to using a terminal emulator wherein the escape codes for things like that are sent to a remote machine. Like I said, I don't use PuTTy, so I've never experienced it. I can set up the bindkeys for that. Give me a few minutes.

**Comment by Eriner** [comment] 2015-12-29 08:56
In general (I guess I should create a separate issue for this), but I don't use the line-editor feature of Zsh. Never have, never will. So when I get around to adding vi/emacs support like prezto has, I will make it's initialization largely optional. Not sure how others feel about it, but it's simply not something I use. The current bindkeys are used to correct emulator issues (like the control sequences you mentioned) and for history-substring-search and the arrow keys, etc. I actually get extremely annoyed when I hit <escape> and it takes me out of 'insert' mode. It's just not something I expect at a terminal. (though, <escape>^ / <escape>$ are useful).

**Comment by GrayShade** [comment] 2015-12-29 08:58
I just tried installing zim here (to `/etc/zsh`) and my cursor disappears, even though I still have prezto in my `$HOME`.

I'm fine with making them optional (perhaps another module). By the way, is there a way to override the modules that are loaded with per-account settings?

**Comment by Eriner** [comment] 2015-12-29 08:59
@GrayShade yes, check your `.zimrc`; that's what it's for.

**Comment by Eriner** [comment] 2015-12-29 09:00
Also, don't use two frameworks. Either use Prezto or Zim. They're bound to cause conflicts.

**Comment by GrayShade** [comment] 2015-12-29 09:02
> Also, don't use two frameworks. Either use Prezto or Zim. They're bound to cause conflicts.

I'm not planning to, I meant that whatever Zim is doing to break the terminal cursor doesn't get fixed by Prezto.

**Comment by Eriner** [comment] 2015-12-29 09:03
@GrayShade Ah, okay. In reference to this, then.

> From another machine with TERM=xterm-256color the cursor disappears when it's not at the end of line. This happens with gnome-terminal.

This is only on gnome-terminal, and does not happen with just prezto, then?

**Comment by GrayShade** [comment] 2015-12-29 09:07
> This is only on gnome-terminal, and does not happen with just prezto, then?
Correct. Apparently it doesn't happen in Zim with urxvt either.

For what it's worth, urxvt sends `^[[7~` for `Home ` and gnome-terminal sends `^[[H`. Now that I think about it, I was testing with home because it seemed to be wired up in the `input` module, but that's not exactly true.

**Comment by GrayShade** [comment] 2015-12-29 09:09
Well, if you think it's just an issue with unbound escapes, I can set them up on my own.

**Comment by Eriner** [comment] 2015-12-29 09:10
So, this is a difficult problem for me to debug, again, because I don't use Windows at all. The cursor disappearing problem, I can reproduce. The others... not so much.

**Comment by Eriner** [comment] 2015-12-29 09:22
Okay, so I can reproduce the cursor issue in uxrvt, but not in any other terminal emulators. There is (in uxrvt) a distinct behavioural difference between prezto and zim. Will work on this shortly.

**Comment by Eriner** [comment] 2015-12-29 09:39
@GrayShade it seems like `syntax-highlighting` is just weird. Disable the `cursor` highlighter in your `.zimrc` and the highlighting problem is solved. I will make a note of this in the template file.

**Comment by GrayShade** [comment] 2015-12-29 09:45
That's right, thanks.

**Comment by Eriner** [comment] 2015-12-29 09:53
Made note of the problem here, as well as disabled 'cursor' as a default highlighter. https://github.com/Eriner/zim/commit/ab99776d4e302c00fef254bc0733613242372016

@GrayShade am I safe to close this issue now, or are there problems still to be addressed?

**Comment by GrayShade** [comment] 2015-12-29 10:02
There's still that issue under PuTTY (which I can now confirm I can't reproduce otherwise).

Perhaps I'll try to take some stuff from prezto to see if that works better. Can we still keep this open for a while?

**Comment by Eriner** [comment] 2015-12-29 10:03
@GrayShade no problem. Also, https://github.com/Eriner/zim/commit/c3130eda38c1b4cb922eab5ddd1b7e43530613f1. changes are explained there, but 'cursor' must be enabled on non-rxvt terminals, basically. re-enabled it by default.

**Comment by Eriner** [comment] 2015-12-29 10:07
@GrayShade to be clear, just hitting the control keys on your keyboard (when in putty) results in them being printed on the screen?

**Comment by Eriner** [comment] 2015-12-29 10:11
@GrayShade OH. Control + Right arrow, Control + Left arrow. I understand now. Geez.

**Comment by GrayShade** [comment] 2015-12-29 10:12
> @GrayShade to be clear, just hitting the control keys on your keyboard (when in putty) results in them being printed on the screen?
`Ctrl-Left` and `Right`, but that's because they aren't bound. Since you're not planning to introduce emacs/Windows-friendly mappings, that's fine.

I still have some issues with other combinations I use (`Ctrl-R`, `Alt-Backspace`), but the weird thing is they work on another machine (via SSH). But perhaps I'll sort those out myself.

**Comment by Eriner** [comment] 2015-12-29 10:13
Have you tried this: http://the.earth.li/~sgtatham/putty/0.55/htmldoc/Chapter4.html#S4.4.4 ?

**Comment by GrayShade** [comment] 2015-12-29 10:15
> Have you tried this: http://the.earth.li/~sgtatham/putty/0.55/htmldoc/Chapter4.html#S4.4.4 ?

It's set to normal mode, as it was before.

**Comment by Eriner** [comment] 2015-12-29 10:16
Right, have you tried both enabling and disabling it? Just curious if that has any effect on the problem.

**Comment by GrayShade** [comment] 2015-12-29 10:23
Not under Windows. With the Linux version it works fine regardless of that settings, but it might have gotten fixed by the `bindkey` calls in my `.zshrc`.

**Comment by Eriner** [comment] 2015-12-29 10:24
Interesting. Keep me posted on anything else you discover/find that may help others (or allow me to fix this in the `init.zsh`). Thanks!

**Comment by GrayShade** [comment] 2015-12-29 10:29
For what it's worth, here are some mappings I found friendly:

```
bindkey '\e[1;5C' forward-word
bindkey '\e[1;5D' backward-word
bindkey '\e[5C' forward-word
bindkey '\e[5D' backward-word
bindkey '\e\e[C' forward-word
bindkey '\e\e[D' backward-word
bindkey '\eOc' forward-word
bindkey '\eOd' backward-word
bindkey '\eOC' forward-word
bindkey '\eOD' backward-word

bindkey '\e[H' beginning-of-line
bindkey '\e[1~' beginning-of-line

bindkey '\e[F' end-of-line
bindkey '\e[4~' end-of-line
```

**Comment by Jguer** [comment] 2015-12-29 10:34
Can confirm on guake terminal, using zsh and zim, keybindings aren't set by default (prints 5C; and 5D;), adding the above mappings to .zshrc fixes the issue.

**Comment by Eriner** [comment] 2015-12-29 10:52
@GrayShade a simple for loop in the init module solves the ctrl+arrow problem elegantly:
```
 bindkey "${key_info[Left]}" backward-char
 bindkey "${key_info[Right]}" forward-char
 
+for key in "${(s: :)key_info[ControlLeft]}"; do
+  bindkey ${key} backward-word
+done
+for key in "${(s: :)key_info[ControlRight]}"; do
+  bindkey ${key} forward-word
+done
+
```

**Comment by Eriner** [comment] 2015-12-29 10:53
The above is (basically) what prezto does. This splits the escape sequences in the variable between spaces, and sets the bindkey appropriately.

**Comment by Eriner** [comment] 2015-12-29 10:55
As for the other keybinds, I think those would be best assigned by a 'vi' or 'emacs' mode. I will work on creating this at some point this week.

**Comment by GrayShade** [comment] 2015-12-29 10:57
Thanks. If you do that, can you also add `^[OC` and `^[OD`? They're just like `^[Oc` and `^[Od`, but PuTTY sends them in one of those modes.

**Comment by Eriner** [comment] 2015-12-29 11:02
@GrayShade I pushed a fix to the 'bindkeys' branch. Mind testing it for me before I merge it into master?
https://github.com/Eriner/zim/tree/bindkeys

**Comment by GrayShade** [comment] 2015-12-29 11:12
Sure, it seems fine. I still have:

```
bindkey '\e[H' beginning-of-line
bindkey '\e[1~' beginning-of-line
bindkey '\e[F' end-of-line
bindkey '\e[4~' end-of-line

bindkey '\e^?' backward-kill-word
```

Ignoring the latter, with gnome-terminal and `TERM=xterm-256color` `Home` is `^[H`, while `"${terminfo[khome]}"` is `^[OH`. This might be a misconfiguration on my side (I don't know the default `$TERM` under gnome-terminal).

**Comment by Eriner** [comment] 2015-12-29 11:24
@GrayShade uh, whoopsie. Didn't realise I never had a ZLE to actually put it into (and use) application mode :) pull and try again, if you would.

**Comment by Eriner** [comment] 2015-12-29 11:25
err, it seems that I borked something in the process.

**Comment by GrayShade** [comment] 2015-12-29 11:30
Hm, your second commit made `Home` and `End` work for me in gnome-terminal, but not under PuTTY.

**Comment by Eriner** [comment] 2015-12-29 11:32
Just pushed a fix to the order that the arrows are bound so that the normal arrow operation isn't overridden. So it now works in gnome-terminal, but not PuTTY?

**Comment by GrayShade** [comment] 2015-12-29 11:38
Yes, I'll reply to you later with what gets sent by PuTTY. By the way, what did you mean by not using the line editor?

**Comment by Eriner** [comment] 2015-12-29 11:40
Right, that was inspecific. I meant entering `normal` vs `insert` mode.

**Comment by Eriner** [comment] 2015-12-29 11:41
setting `bindkey -v` or `bindkey -e`

**Comment by Eriner** [comment] 2015-12-29 11:44
Currently, ZSH interprets this value automatically by looking at your environment settings. I could add an option in `.zimrc` to make it explicit, but it's not a pressing issue at the moment.

**Comment by GrayShade** [comment] 2015-12-29 12:14
Oh, so you use the vi mode. But Ctrl and arrows also work in (neo)vim by default these days, so I hope you won't find that binding those takes it too far away from vim ☺️.

**Comment by Eriner** [comment] 2015-12-29 12:22
@GrayShade oh, I don't have a problem with vi/emacs/whatever mode, I just don't really use them in Zsh. I just don't use the mode-switching feature. And yes, I also use neovim. :+1:

**Comment by Eriner** [comment] 2015-12-29 12:38
After we get the PuTTY issue sorted, I think it would be safe to close this issue and merge the changes in the bindkey branch into master.

**Comment by GrayShade** [comment] 2015-12-29 14:05
Hmm, I tested on PuTTY:
* PuTTY works in shell with `TERM=xterm` (default), but neovim doesn't like `Home` and `End`. Not related to zim, I suppose. 
* Linux PuTTY needs `\e[1~` and `\e[4~` for `Home` and `End` when `TERM=xterm`, works fine with `putty-256color`. No delay/timeout issue.
* Windows PuTTY needs `\e[C` and `\e[D` for Ctrl-arrows when `TERM=xterm`; No delay/timeout issue.
* With PuTTY and `TERM=putty-256color` (which apparently should be used [1]), `smkx` is not supported. prezto checks for that [2].

You can add those four bindings, but I don't care for them, as I'm using `putty-256colors`. They're just a workaround for a broken `$TERM` (though that's a common setting, I guess).

If you add checks for `smkx` and `rmkx`, this seems fixed to me.

[1] http://blog.sanctum.geek.nz/putty-configuration/
[2] https://github.com/sorin-ionescu/prezto/blob/master/modules/editor/init.zsh#L119

**Comment by Eriner** [comment] 2015-12-29 14:07
Great, I'll add that check, squash, and merge into master. Thanks for all your help @GrayShade, I appreciate it!

**Closed by Eriner** 2015-12-29 14:07 UTC

**Comment by Eriner** [comment] 2015-12-29 14:13
https://github.com/Eriner/zim/commit/641ade3fbd925297067d59594799028c10eb1389 should have taken care of these issues. Thanks again!
